### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by JMiranda421** [ksu-is/FishTrackingSoftware#1]
- [x] Review CVTracer software and identify which ideas could be utilized in this project

- [x] Begin writing code for project and attempt to get a running, working line of code

- [x] Utilize various search engines to get a better understanding of what is required to operate this code. (i.e Required software, physical technology, third party apps, etc.)
